spring:
  application:
    name: lab-spring-ai
  ai:
    openai:
      # Gemini API : 시스템 환경변수에 GOOGLE_API_KEY 변수에 API 키를 미리 설정했음. 
      api-key: ${GOOGLE_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        completions-path: v1beta/openai/chat/completions
        options:
          # 사용할 모델을 지정.
          model: gemini-2.5-flash
          # Step 5 (Tool Calling)
          # model: llama-3.3-70b-versatile
          max-tokens: 1024

logging:
  level:
    egovframework.lab.ai: DEBUG
    org.springframework.ai.model.tool.autoconfigure.ToolCallingAutoConfiguration: WARN
